#!/usr/bin/python

# This script launches a terminal with the appropriate WINEPREFIX set.

import os
import sys
import subprocess

# Initialization Variables:

home = os.path.expanduser("~")
prefixDir = home + "/.wineprefix"


# Returns a list of existing prefixes.
def prefixDirs():
    prefixes = next(os.walk(prefixDir))[1]
    return(prefixes)

# Checks to see if the desired prefix exists.
def isExisting(prefix):
    # First, if ~/.wineprefix doesn't exist, then it's an automatic false.
    if not os.path.exists(prefixDir):
        return False

    # Now for checks.  
    valid = 0
    for option in prefixDirs():
        filename = prefixDir + "/" + option + "/" + "system.reg"
        
        # We're going to see if the wineprefix directory exists.
        if prefix == option:
            # Then, we're going to see if "system.reg" is present.
            if os.path.isfile(filename):
                valid = 1

    # After these checks, if "valid" has been set to "1", then there is a match.
    if valid == 1:
        return True
    else:
        return False

# Now, we want something to show all installed prefixes.
def showExistingPrefixes():
    print("These prefixes are currently installed:")
    totalDirs = 0
    
    prefixDirectories = prefixDirs()
    
    for i in range(0, len(prefixDirectories)):
        if isExisting(prefixDirectories[i]):
            totalDirs += 1
            print("* " + prefixDirectories[i] + " (" + prefixDir + "/" + prefixDirectories[i] + ")")

    if totalDirs == 0:
        print("* No prefixes are currently installed.")

# Argument bounds checking is important. We want either no arguments (usage and existing prefix
# list) or one argument (make a new prefix).  If we want a batch process, we can use a do loop.
# NOTE: the command is always one argument, so "1" means no arguments, while "2" means one
# argument.

def noArguments():
    if len(sys.argv) == 1:
        return True
    else:
        return False

def oneArgument():
    if len(sys.argv) == 2:
        return True
    else:
        return False

##### Main Loop #####

## First, we do command bounds checking.

# The first thing we check: make sure there is a maximum of one option.
if (not noArguments()) and (not oneArgument()):
    print (os.path.basename(sys.argv[0]) + " cannot take more than one argument (the name of the prefix)")

if noArguments():
    print("Usage:   " + os.path.basename(sys.argv[0]) + " <name of prefix>\n")
    showExistingPrefixes()

if oneArgument():
    if not isExisting(sys.argv[1]):
        print ("The prefix \"" + sys.argv[1] + "\" does not exist.\n")
        showExistingPrefixes()
    else:
        os.environ['WINEPREFIX'] = prefixDir + "/" + sys.argv[1]
        subprocess.call('cd ' + prefixDir + '/' + sys.argv[1] + '; xterm', shell=True)
